# Generated by Django 4.0 on 2023-08-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256, verbose_name='Website url')),
                ('title', models.CharField(default='Oil Mill', max_length=256, verbose_name='название сайта')),
                ('email', models.EmailField(default='OILMILL@EMAIL.COM', max_length=254, verbose_name='электронная почта')),
                ('phone', models.CharField(default='+7 (7172) 77 77 77', max_length=256, verbose_name='телефон')),
                ('address', models.CharField(default='Г. АСТАНА, УЛ. ПРОМЫШЛЕННАЯ, ЗД.1', max_length=256, verbose_name='адрес')),
                ('telegram', models.CharField(default='@oil_mill', max_length=256, verbose_name='telegram')),
                ('whatsapp', models.CharField(default='whatsapp://send?phone=77172777777', max_length=256, verbose_name='whatsapp')),
                ('viber', models.CharField(default='viber://chat?number=77172777777', max_length=256, verbose_name='viber')),
                ('vk', models.CharField(default=' https://vk.com/oilmill', max_length=256, verbose_name='vk')),
                ('skype', models.CharField(default='techno', max_length=256, verbose_name='skype')),
                ('facebook', models.CharField(default='https://facebook.com/megano', max_length=256, verbose_name='facebook')),
                ('twitter', models.CharField(default='https://twitter.com/megano', max_length=256, verbose_name='twitter')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='дата обновления')),
            ],
            options={
                'verbose_name_plural': 'Настройки',
                'db_table': 'settings',
            },
        ),
    ]
